import type { Metadata } from 'next';
import './globals.css';
import { Container } from '@/components/container';
import { Header } from '@/components/Header';

export const metadata: Metadata = {
  title: {
    default: 'Create Next App',
    template: '%s | The Blog',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className='dark'>
      <body>
        <Container>
          <Header />

          {children}
        </Container>
      </body>
    </html>
  );
}
